repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: mixed-line-ending
        args: ['--fix=auto']
-   repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        args: ['--check']