[tool.poetry]
name = "sexybabeycord"
version = "1.0"
description = "Sexybabeycord is a multi-purpose discord bot that handles many different features in the form of cogs. The list of cogs grows and shrinks with the activities of the server."
authors = ["Vaughn Woerpel <vaughnwoerpel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
Wand = "^0.6.11"
aiohttp = "^3.9.3"
beautifulsoup4 = "^4.12.3"
"discord.py" = "^2.3.1"
pydub = "^0.25.1"
requests = "^2.31.0"
validators = "^0.22.0"
speechrecognition = "^3.10.1"
twscrape = "^0.11.1"
coloredlogs = "^15.0.1"
flakeheaven = "^3.3.0"
dpytest = "^0.7.0"
python-magic = "^0.4.27"
pre-commit = "^3.3.3"
pre-commit-hooks = "^4.4.0"
deptry = "^0.12.0"
pynacl = "^1.5.0"
libmagic = "^1.0"
opencv-python = "^4.9.0.80"
yt-dlp = "^2023.12.30"
pymongo = "4.6.2"
croniter = "^2.0.2"
dnspython = "^2.6.1"
pillow = "^10.2.0"
numpy = "^1.26.4"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
testpaths = [
    "tests"
]
