[tool.poetry]
name = "sexybabeycord"
version = "0.1.1"
description = "Sexybabeycord is a multi-purpose discord bot that handles many different features in the form of cogs. The list of cogs grows and shrinks with the activities of the server."
authors = ["Vaughn Woerpel"]
readme = "README.md"
packages = [{ include = "**/*" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
Wand = "^0.6.11"
aiohttp = "^3.9.3"
beautifulsoup4 = "^4.12.2"
"discord.py" = "^2.3.1"
pydub = "^0.25.1"
requests = "^2.31.0"
validators = "^0.20.0"
speechrecognition = "^3.10.0"
twscrape = "^0.6.0"
coloredlogs = "^15.0.1"
dpytest = "^0.7.0"
pre-commit = "^3.3.3"
deptry = "^0.12.0"
pynacl = "^1.5.0"
opencv-python = "^4.8.0.74"
yt-dlp = "^2023.12.30"
pymongo = "^4.6.1"
croniter = "^2.0.1"
dnspython = "^2.4.2"
pillow = "^10.2.0"
numpy = "^1.26.1"
rembg = "^2.0.52"
magika = "^0.5.0"
python-dotenv = "^1.0.1"
ruff = "^0.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
testpaths = [
    "tests"
]
