[tool.poetry]
name = "sexybabeycord"
version = "0.1.0"
description = "Sexybabeycord is a multi-purpose discord bot that handles many different features in the form of cogs. The list of cogs grows and shrinks with the activities of the server."
authors = ["Vaughn Woerpel"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"
Wand = "^0.6.11"
aiohttp = "^3.8.4"
beautifulsoup4 = "^4.12.2"
"discord.py" = "^2.3.1"
pydub = "^0.25.1"
requests = "^2.31.0"
validators = "^0.20.0"
speechrecognition = "^3.10.0"
twscrape = "^0.6.0"
black = "^23.7.0"
isort = "^5.12.0"
coloredlogs = "^15.0.1"
flakeheaven = "^3.3.0"
dpytest = "^0.7.0"
python-magic = "^0.4.27"
pre-commit = "^3.3.3"
pre-commit-hooks = "^4.4.0"
pyupgrade = "^3.10.1"
deptry = "^0.12.0"
pynacl = "^1.5.0"
libmagic = "^1.0"
opencv-python = "^4.8.0.74"
moviepy = "^1.0.3"
youtube-dl = "^2021.12.17"
yt-dlp = "^2023.7.6"
pymongo = "^4.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
testpaths = [
    "tests"
]
