name: build and test

on:
  workflow_call

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
  
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6
  
    - name: Install poetry
      run: |
        python -m pip install poetry
  
    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true
  
    - name: Cache the virtualenv
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
   
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
  
    - name: Install dependencies
      run: |
        python -m poetry install
        
    - name: Run tests
      env:
        TENOR_TOKEN: ${{SECRETS.TENOR_TOKEN}}
      run: |
        poetry run python -m pytest
