on:
  workflow_call

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            cd ${{ secrets.REMOTE_TARGET }}
            docker stop sexybabeycord 2&>1 /dev/null
            docker rm sexybabeycord 2&>1 /dev/null
            docker rmi ghcr.io/vaughnw128/sexybabeycord:latest 2&>1 /dev/null
            docker run -d -t --name sexybabeycord -v ./accounts.json:/bot/accounts.json -v ./.env:/bot/.env --pull always ghcr.io/vaughnw128/sexybabeycord:latest
